version: "3.8"
services:
  # backend:
  #   build: .
  #   container_name: backend
  #   ports:
  #     - 8000:8000
  #     - 9229:9229 # Debugger port
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules # trick to node_modules not mapping from host to container
  #   command: yarn start:docker # Override Dockerfile CMD
  #   environment:
  #     - PORT=8000
  #   depends_on:
  #     - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "3308:3306"

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    depends_on:
      - mariadb
    ports:
      - 7777:8080

volumes:
  db_data:
